Fix/#6461 swagger decorator
US-EPA-CAMD/easey-qa-certification-api pull request #624
Opened 2024-12-13 14:05 UTC by yonatan-dp

## Pull Request

Now referencing swagger decorator from easey-common. Removed /workspace endpoints from swagger

2024-12-17 17:42 UTC, ergjustin requested changes
In the easy-common package, https://github.com/US-EPA-CAMD/easey-common/blob/master/src/utilities/swagger-decorator.const.ts#L10 is currently receiving an invalid value. It should be set to `const env= this.configService.get("app.env")` instead.

2024-12-17 17:51 UTC, yonatan-dp commented
> In the easy-common package, https://github.com/US-EPA-CAMD/easey-common/blob/master/src/utilities/swagger-decorator.const.ts#L10 is currently receiving an invalid value. It should be set to `const env= this.configService.get("app.env")` instead.

PR created for this fix: https://github.com/US-EPA-CAMD/easey-common/pull/195

2024-12-31 15:27 UTC, ergjustin submitted a review, later dismissed
Looks good to me

2025-01-08 16:09 UTC, ergjustin approved these changes

2025-01-08 16:09 UTC, merged